version: '3.5'

services:
  frontend_3.1:
    image: ilmariky/frontend_3.1
    ports: 
        - 5000:5000 
    container_name: frontend_3.1

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower