version: '3.5'

services:
  youtube-dl_3.1:
    image: ilmariky/youtube-dl_3.1
    container_name: youtube-dl_3.1

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower